### ISSUE TITLE
[S1-PBI6]Membuat halaman memutar musik

### ISSUE THREAD

**Issue by anisawahyup** [SI-RPL-2023/SI4405_C_WeatherGo#8]

**Comment by jaaak24** [comment]
![Image](https://user-images.githubusercontent.com/115634711/228160594-c6ef589f-52c2-4571-ab15-399bd9049a08.png)
![Image](https://user-images.githubusercontent.com/115634711/228160701-dcbb4898-6955-441e-868e-9d57b9ece139.png)
